# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audience=${AUTH0_AUDIENCE}

# Vaadin (modo producción)
vaadin.productionMode=true

# Para producción en Render
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}